kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-a
      environment: develop
      system: system-x
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: app-a
        environment: develop
        system: system-x
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: quarkus-app
          securityContext: {}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'docker.io/saiello/quarkus-greeting-api'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
