apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: private-clone-read
spec:
  description: | 
    This pipeline clones a git repo, then echoes the README file to the stdout.
  # A list of parameters to be used by the Tasks in this Pipeline
  params:
  - name: repo-url
    type: string
    description: The git repo URL to clone from.  

  # A shared volume used by the Tasks to store the code
  workspaces:
  - name: shared-data
    description: | 
      This workspace contains the cloned repo files, so they can be read by the
      next task.    
  - name: repo-basic-auth
  tasks:
  - name: fetch-source
    taskRef:
      # A ClusterTask: use `tkn clustertask ls` to verify it is available
      kind: ClusterTask
      name: git-clone
    workspaces:
      # Link the Task's workspace "output" to the Pipeline's workspace "shared-data"
    - name: output
      workspace: shared-data
    - name: basic-auth
      workspace: repo-basic-auth
    params:
    - name: url
      value: $(params.repo-url)      
