---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gitlab-trigger-pipeline
spec:
  params:
  - name: git-repo-url
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: gitlab-pipeline-run-
    spec:
      pipelineRef:
        name: gitlab-pipeline
    workspaces:
    - name: repo-basic-auth
      secret: 
        secretName: git-basic-auth-secret

    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    params:
    - name: repo-url
      value: $(tt.params.git-repo-url) 
    - name: repo-revision 
      value: $(tt.params.git-repo-revision)
