---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: gitlab-event-listener
  name: el-gitlab-event-listener
spec:
  port:
    targetPort: http-listener
  to:
    kind: ""
    name: el-gitlab-event-listener
