apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-test-gitops
stringData:
  password: <GT_TOKEN>
  type: git
  url: git@github.com:saiello/test-gitops.git
  username: <GT_USER>