kind: Secret
apiVersion: v1
metadata:
  name: git-basic-auth-secret
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://gitlab.private.repo.com"]
      helper = store
  .git-credentials: |
    https://saiello:XXX@gitlab.private.repo.com
