apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: edit-readme
spec:
  workspaces:
    - name: source
  steps:
    - name: edit
      image: registry.redhat.io/ubi9/toolbox
      workingDir: $(workspaces.source.path)
      script: |
        echo "Foobar" >> README.md
