---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: bitbucket-event-listener
spec:
  triggers:
  
  - name: bitbucket-pipeline
    interceptors:
    - ref:
        name: "bitbucket"
      params:
        - name: eventTypes
          value:
            - repo:push
    bindings:
    - ref: bitbucket-binding
    template:
      ref: bitbucket-trigger-pipeline
